[flags]
autohide_time = true
rate = 777
# Whether to put the CPU legend to the left.
left_legend = true
group_processes = true
regex = true
default_time_value = 77777
time_delta = 17777
hide_table_gap = true
color = "gruvbox"
