[flags]
autohide_time = true
rate = 777
# Whether to put the CPU legend to the left.
left_legend = true
group_processes = true
regex = true
hide_table_gap = true
dot_marker = true

[temp_filter]
is_list_ignored = true
list = ["cpu", "wifi", "hwmon"]
regex = true
case_sensitive = false
whole_word = false

[[row]]
  ratio=30
  [[row.child]]
  type="cpu"
[[row]]
    ratio=40
    [[row.child]]
      ratio=3
      [[row.child.child]]
        type="temp"
    [[row.child]]
      ratio=4
      type="mem"
[[row]]
  ratio=30
  [[row.child]]
    type="proc"
    default=true
