#!/bin/sh

s="  " # field separator

filename="${1##*/}"
filesize=$(du -Hh "$1" | awk '{print $1}')

geometry="${2}x${3}"

## This is cool, but in my entire image collection only 4 images have tags...
# tags=$(exiv2 -qpi pr "$1" | awk '$1~"Keywords" { printf("%s,", $4); }')
# tags=${tags%,}

timestamp="$(exiv2 -qg Exif.Image.DateTime -Pv "$1")"

echo "${filesize}${s}${geometry}${tags:+$s}${tags}${s}${filename}${timestamp:+${s}${timestamp}}"
