#!/bin/bash

set -C -f -u
IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}"

# Script arguments
FILE_PATH="$(realpath "${1}")"         # Full path of the highlighted file
WIDTH="${2}"
HEIGHT="${3}"

#FILE_EXTENSION="${FILE_PATH##*.}"
#FILE_EXTENSION_LOWER=$(echo ${FILE_EXTENSION} | tr '[:upper:]' '[:lower:]')

# Settings
HIGHLIGHT_SIZE_MAX=262143  # 256KiB
HIGHLIGHT_TABWIDTH=8
HIGHLIGHT_STYLE='pablo'

handle_mime() {
    local mimetype="${1}"
    case "$(basename ${FILE_PATH})" in
	    *.md) glow -w 80 "${FILE_PATH}";;
	    *)
	    case "${mimetype}" in
		text/html) w3mwrap -dump "${FILE_PATH}" ;;
		text/troff) man ./ "${FILE_PATH}" | col -b ;;
		text/* | */xml | */json)
		    if [ "$( stat --printf='%s' -- "${FILE_PATH}" )" -gt "${HIGHLIGHT_SIZE_MAX}" ]; then
			exit 2
		    fi
		    if [ "$( tput colors )" -ge 256 ]; then
			local highlight_format='xterm256'
		    else
			local highlight_format='ansi'
		    fi
		    highlight --replace-tabs="${HIGHLIGHT_TABWIDTH}" --out-format="${highlight_format}" \
			--style="${HIGHLIGHT_STYLE}" --force -- "${FILE_PATH}" ;;
		application/zip | application/x-bzip2 | application/x-bzip | applicatio/x-gzip | application/x-xz | rar | application/x-rar-compressed | application/x-tar | application/x-rar | application/x-7z-compressed) atool --list -- "${FILE_PATH}" ;;
		application/msword) catdoc "${FILE_PATH}" ;;
		application/csv) csview --style reinforced "${FILE_PATH}" ;;
		*/pdf) pdftotext -l 10 -nopgbrk -q -- "${FILE_PATH}" - ;;
		*djvu*) djvutxt "${FILE_PATH}" ;;
		image/*) chafa --fill=space --symbols=block -c 240 -s "${WIDTH}"x"${HEIGHT}" "${FILE_PATH}" || exit 1;;
		video/* | audio/*|application/octet-stream) mediainfo "${FILE_PATH}" | sed 's/  \+:/: /;' || exit 1;;
		*opendocument*) odt2txt "${FILE_PATH}" ;;
		*torrent*) { echo "$(eval 'dump_torrent "${FILE_PATH}"')" | head -n 200; exit 5; } || exit 1;;
    	    esac;;
    esac
}

MIMETYPE="$( file --dereference --brief --mime-type -- "${FILE_PATH}" )"
handle_mime "${MIMETYPE}"
exit 1
