#!/bin/sh

# Useful misc
	dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS 2>/dev/null
	/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & # Start Polkit

# Screensaver
	xss-lock -- /usr/local/bin/slock &

# Utils
	xrdb -load ~/.config/X11/Xresources
	[ -f ~/.cache/wal/active ] && wal -R || sbg # Dirty trick to check if pywal was on at shutdown
	touchpadtoggle			# Disable touchpad by default
	remaps				# Switch caps/super and one-tap_caps/esc
	copyq &				# Clipboard management
	pgrep redshift &> /dev/null || redshift &> /dev/null & # Color temperature
	picom &				# Compositor
	unclutter &			# Remove mouse when idle
	mconnect 2>/dev/null & 		# Autoconnect to Android
	mpDris2 &			# Start an mpd MPRIS interface
	transmission-daemon &		# Bittorrent daemon
