#!/bin/sh

# Useful misc
	dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS 2>/dev/null
	/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & # Start Polkit
	eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
	export SSH_AUTH_SOCK

# Screensaver
	xss-lock -- /usr/local/bin/slock &

# Daemons which may be started by systemd, when I use it.
	_() {
	    pgrep -x "$1" > /dev/null ||
		{ "$@" & }
	}
	_ dunst
	_ mpd

# Utils
	xrdb -load ~/.config/X11/Xresources
	[ -f ~/.cache/wal/active ] && wal -R || sbg # Dirty trick to check if pywal was on at shutdown
	touchpadtoggle			# Disable touchpad by default
	remaps				# Switch caps/super and one-tap_caps/esc
	_ copyq				# Clipboard management
	_ redshift			# Color temperature
	_ picom				# Compositor
	unclutter &			# Remove mouse when idle
	mconnect 2>/dev/null & 		# Autoconnect to Android
	_ transmission-daemon		# Bittorrent daemon
