#!/bin/sh

# Dim->LockScreen->Suspend
	xset s 180 60
	xss-lock -n "/home/fra/.local/bin/scripts/dim" -- /usr/local/bin/slock &
	xidlehook --not-when-fullscreen --not-when-audio --timer 600 "systemctl suspend" - &

	_() {	# Used to start daemons which have not been started yet
	    pgrep -x "$1" > /dev/null ||
		{ "$@" & }
	}
	_ dunst
	_ mpd
	xsetroot -cursor_name left_ptr # Needed because of hsetroot
	mon -e					# Monitor selection
	[[ -f ~/.config/X11/Xresources ]] && xrdb -load ~/.config/X11/Xresources
	[ -f ~/.cache/wal/active ] && wal -R || sbg # Dirty trick to check if pywal was on at shutdown
	_ redshift			# Color temperature
	togcomp -y			# Compositor
	remaps					# Switch caps/super and one-tap_caps/esc
	copyq &					# Clipboard management
	gebaard -b			# Gesture daemon
	xbanish -i shift -i mod4 -i control & # Remove mouse when typing
	_ subs -d				# Start custom yt daemon
