#!/bin/sh

# xinitrc runs automatically when you run startx.

[ -f "$HOME/.xprofile" ] && . "$HOME/.xprofile"
remaps &			# switch caps/super and one-tap_caps/esc, in gnome-shell I only want it as Esc
dunst &				# dunst for notifications, which stays here as I do not want it in gnome-shell

ssh-agent dwm
# if dwm exits 0, restart -- this allows hot reloading of config.h
while type dwm >/dev/null ; do dwm && continue || break ; done

# vim:ft=config
