#!/bin/sh

dbus-update-activation-environment --verbose --systemd DBUS_SESSION_BUS_ADDRESS 2>/dev/null
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & # Start Polkit

# xscreensaver -no-splash &
xset s 600
xss slock &

xrdb -merge -I$HOME ~/.Xresources
mconnect 2>/dev/null &		# Autoconnect to mconnect saved devices
transmission-daemon &		# bittorrent
copyq &				# Clipboard management
xcompmgr &			# xcompmgr for transparency
remaps &			# Switch caps/super and one-tap_caps/esc
setbg &				# Basically xwallpaper
dunst &				# Notifications
redshift &			# Color temperature
xset r rate 300 50 &		# Speed xrate up
unclutter &			# Remove mouse when idle
