use_nerdfont=true

[keybindings]
"Ctrl+d" = "move down 5"
"Ctrl+u" = "move up 5"
"G" = "move bottom"
"gg" = "move top"

#spotify
[theme]
background = "#073642"
primary = "#fcf4dc"
secondary = "#475b62"
title = "#738a05"
playing = "#738a05"
playing_bg = "#002831"
highlight = "#eae3cb"
highlight_bg = "#484848"
error = "#eae3cb"
error_bg = "#d11c24"
statusbar = "#002831"
statusbar_progress = "#738a05"
statusbar_bg = "#738a05"
cmdline = "#eae3cb"
cmdline_bg = "#475b62"

#b16_sol_dark
#[theme]
#background = "#002b36"
#primary = "#93a1a1"
#secondary = "#008b8b"
#title = "#eee8d5"
#playing = "#eee8d5"
#playing_bg = "#002b36"
#highlight = "#93a1a1"
#highlight_bg = "#484848"
#error = "#93a1a1"
#error_bg = "#fdf6e3"
#statusbar = "#002b36"
#statusbar_progress = "#b22222"
#statusbar_bg = "#859900"
#cmdline = "#93a1a1"
#cmdline_bg = "#002b36"
