use_nerdfont=true

[keybindings]
"Ctrl+d" = "move down 5"
"Ctrl+u" = "move up 5"
"G" = "move bottom"
"gg" = "move top"

# # Spotify
# [theme]
# background = "#073642"
# primary = "#fcf4dc"
# secondary = "#475b62"
# title = "#738a05"
# playing = "#738a05"
# playing_bg = "#002831"
# highlight = "#eae3cb"
# highlight_bg = "#484848"
# error = "#eae3cb"
# error_bg = "#d11c24"
# statusbar = "#002831"
# statusbar_progress = "#738a05"
# statusbar_bg = "#738a05"
# cmdline = "#eae3cb"
# cmdline_bg = "#475b62"

# # Base16_sol_dark, modified closer to spotify colors by BachoSeven, originally https://github.com/gidsi/base16-ncspot
# [theme]
# background = "#002b36"
# primary = "#eee8d5"
# secondary = "#2aa198"
# title = "#859900"
# playing = "#268bd2"
# playing_bg = "#002b36"
# highlight = "#93a1a1"
# highlight_bg = "#484848"
# error = "#93a1a1"
# error_bg = "#fdf6e3"
# statusbar = "#002b36"
# statusbar_progress = "#dc322f"
# statusbar_bg = "#859900"
# cmdline = "#93a1a1"
# cmdline_bg = "#002b36"

# Gruvbox dark [ based on base16 by Dawid Kurek (dawikur@gmail.com) ]
[theme]
background = "#282828"
primary = "#d5c4a1"
secondary = "#458588"
title = "#fbf1c7"
playing = "#b16286"
playing_bg = "#282828"
highlight = "#d5c4a1"
highlight_bg = "#555555"
error = "#d5c4a1"
error_bg = "#fbf1c7"
statusbar = "#1d2021"
statusbar_progress = "#8ec07c"
statusbar_bg = "#98971a"
cmdline = "#d5c4a1"
cmdline_bg = "#282828"
