use_nerdfont=true

[keybindings]
"Ctrl+d" = "move down 5"
"Ctrl+u" = "move up 5"
"G" = "move down 800"
"g" = "move up 800"

#spotify
#[theme]
#background = "black"
#primary = "light white"
#secondary = "light black"
#title = "green"
#playing = "green"
#playing_bg = "black"
#highlight = "light white"
#highlight_bg = "#484848"
#error = "light white"
#error_bg = "red"
#statusbar = "black"
#statusbar_progress = "green"
#statusbar_bg = "green"
#cmdline = "light white"
#cmdline_bg = "black"

#b16_sol_dark
[theme]
background = "#002b36"
primary = "#93a1a1"
secondary = "#008b8b"
title = "#eee8d5"
playing = "#eee8d5"
playing_bg = "#002b36"
highlight = "#93a1a1"
highlight_bg = "#484848"
error = "#93a1a1"
error_bg = "#fdf6e3"
statusbar = "#002b36"
statusbar_progress = "#b22222"
statusbar_bg = "#859900"
cmdline = "#93a1a1"
cmdline_bg = "#002b36"
