use_nerdfont=true

[keybindings]
"Ctrl+d" = "move down 5"
"Ctrl+u" = "move up 5"
"G" = "move bottom"
"gg" = "move top"

# # Spotify
# [theme]
# background = "#073642"
# primary = "#fcf4dc"
# secondary = "#475b62"
# title = "#738a05"
# playing = "#738a05"
# playing_bg = "#002831"
# highlight = "#eae3cb"
# highlight_bg = "#484848"
# error = "#eae3cb"
# error_bg = "#d11c24"
# statusbar = "#002831"
# statusbar_progress = "#738a05"
# statusbar_bg = "#738a05"
# cmdline = "#eae3cb"
# cmdline_bg = "#475b62"

# Base16_sol_dark
# [theme]
# background = "#002b36"
# primary = "#eee8d5"
# secondary = "#008b8b"
# title = "#859900"
# playing = "#268bd2"
# playing_bg = "#002b36"
# highlight = "#93a1a1"
# highlight_bg = "#484848"
# error = "#93a1a1"
# error_bg = "#fdf6e3"
# statusbar = "#002b36"
# statusbar_progress = "#dc322f"
# statusbar_bg = "#859900"
# cmdline = "#93a1a1"
# cmdline_bg = "#002b36"

# Base16 Gruvbox dark, medium - ncspot color config [ Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox) ]
[theme]
background = "#282828"
primary = "#d5c4a1"
secondary = "#3c3836"
title = "#ebdbb2"
playing = "#ebdbb2"
playing_bg = "#282828"
highlight = "#d5c4a1"
highlight_bg = "#504945"
error = "#d5c4a1"
error_bg = "#fbf1c7"
statusbar = "#282828"
statusbar_progress = "#cc241d"
statusbar_bg = "#98971a"
cmdline = "#d5c4a1"
cmdline_bg = "#282828"
