#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
 for _ in /etc/X11/xinit/xinitrc.d/?*.sh; do
  [ -x "$_" ] && . "$_"
 done
 unset _
fi

[ -f "$XDG_CONFIG_HOME/X11/xprofile" ] && . "$XDG_CONFIG_HOME/X11/xprofile"

ssh-agent "${WM:-dwm}" > /tmp/dwmlog 2>&1
systemctl --user stop clipmenud.service
